import ProductPageClient from './ProductPageClient';

// Base de datos mock de productos
// Base de datos mock de productos - COMPLETA
const allProducts = [
  // MEDICINAS
  { 
    id: 1, 
    slug: 'paracetamol-500mg',
    name: 'Paracetamol 500mg',
    fullName: 'Paracetamol 500mg (Caja x 20 tabletas)',
    code: '1002498SP',
    category: 'Medicinas',
    brand: 'Genérico',
    price: 2.50,
    oldPrice: 3.00,
    discount: 17,
    stock: 45,
    images: [
      'https://placehold.co/600x600/e3f2fd/1976d2?text=💊+Paracetamol+500mg',
      'https://placehold.co/600x600/e3f2fd/1976d2?text=Caja+x+20',
      'https://placehold.co/600x600/e3f2fd/1976d2?text=Vista+Lateral',
    ],
    description: 'Analgésico y antipirético efectivo para el alivio del dolor leve a moderado y reducción de la fiebre. Ideal para dolores de cabeza, dolor dental, dolores musculares y síntomas de resfriado.',
    indications: 'Indicado para el alivio sintomático del dolor leve a moderado, incluyendo dolor de cabeza, dolor dental, dolores musculares y menstruales.',
    contraindications: 'No debe usarse en caso de hipersensibilidad conocida al paracetamol. Contraindicado en enfermedad hepática grave.',
    dosage: 'Adultos: 1-2 tabletas cada 4-6 horas según necesidad. No exceder 8 tabletas en 24 horas.',
  },
  { 
    id: 4, 
    slug: 'ibuprofeno-400mg',
    name: 'Ibuprofeno 400mg',
    fullName: 'Ibuprofeno 400mg (Caja x 30 tabletas)',
    code: '1002499SP',
    category: 'Medicinas',
    brand: 'Genérico',
    price: 4.20,
    oldPrice: 5.00,
    discount: 16,
    stock: 3,
    images: [
      'https://placehold.co/600x600/e3f2fd/1976d2?text=💊+Ibuprofeno+400mg',
      'https://placehold.co/600x600/e3f2fd/1976d2?text=Caja+x+30',
      'https://placehold.co/600x600/e3f2fd/1976d2?text=Vista+Lateral',
    ],
    description: 'Antiinflamatorio no esteroideo (AINE) para el alivio del dolor e inflamación. Efectivo para dolores musculares y articulares.',
    indications: 'Dolor de cabeza, dolor muscular, artritis, dolor dental, cólicos menstruales, fiebre.',
    contraindications: 'No usar en caso de úlcera gástrica activa o hipersensibilidad a AINEs. Evitar en embarazo.',
    dosage: 'Adultos: 1 tableta cada 6-8 horas. No exceder 1200mg al día. Tomar con alimentos.',
  },
  { 
    id: 8, 
    slug: 'amoxicilina-500mg',
    name: 'Amoxicilina 500mg',
    fullName: 'Amoxicilina 500mg (Caja x 21 cápsulas)',
    code: '1002503SP',
    category: 'Medicinas',
    brand: 'Genérico',
    price: 9.30,
    oldPrice: 11.00,
    discount: 15,
    stock: 25,
    images: [
      'https://placehold.co/600x600/e3f2fd/1976d2?text=💊+Amoxicilina+500mg',
      'https://placehold.co/600x600/e3f2fd/1976d2?text=Caja+x+21',
      'https://placehold.co/600x600/e3f2fd/1976d2?text=Vista+Lateral',
    ],
    description: 'Antibiótico de amplio espectro para el tratamiento de infecciones bacterianas. Pertenece al grupo de las penicilinas.',
    indications: 'Infecciones respiratorias, urinarias, de piel y tejidos blandos causadas por bacterias sensibles.',
    contraindications: 'Hipersensibilidad a penicilinas o cefalosporinas. No usar en mononucleosis infecciosa.',
    dosage: 'Adultos: 1 cápsula cada 8 horas durante 7-10 días. Completar el tratamiento completo.',
  },
  { 
    id: 11, 
    slug: 'aspirina-500mg',
    name: 'Aspirina 500mg',
    fullName: 'Aspirina 500mg (Caja x 20 tabletas)',
    code: '1002501SP',
    category: 'Medicinas',
    brand: 'Genérico',
    price: 3.50,
    oldPrice: 4.20,
    discount: 17,
    stock: 60,
    images: [
      'https://placehold.co/600x600/e3f2fd/1976d2?text=💊+Aspirina+500mg',
      'https://placehold.co/600x600/e3f2fd/1976d2?text=Caja+x+20',
      'https://placehold.co/600x600/e3f2fd/1976d2?text=Vista+Lateral',
    ],
    description: 'Analgésico, antipirético y antiinflamatorio de uso común. También utilizado en prevención cardiovascular.',
    indications: 'Dolor leve a moderado, fiebre, prevención de eventos cardiovasculares en pacientes de riesgo.',
    contraindications: 'No usar en niños menores de 12 años. Evitar en caso de úlcera gástrica o trastornos de coagulación.',
    dosage: 'Adultos: 1-2 tabletas cada 4-6 horas. No exceder 4g al día. Tomar con alimentos.',
  },
  { 
    id: 12, 
    slug: 'naproxeno-250mg',
    name: 'Naproxeno 250mg',
    fullName: 'Naproxeno 250mg (Caja x 20 tabletas)',
    code: '1002500SP',
    category: 'Medicinas',
    brand: 'Genérico',
    price: 5.80,
    oldPrice: 7.00,
    discount: 17,
    stock: 30,
    images: [
      'https://placehold.co/600x600/e3f2fd/1976d2?text=💊+Naproxeno+250mg',
      'https://placehold.co/600x600/e3f2fd/1976d2?text=Caja+x+20',
      'https://placehold.co/600x600/e3f2fd/1976d2?text=Vista+Lateral',
    ],
    description: 'Antiinflamatorio de acción prolongada para dolor e inflamación. Efecto de hasta 12 horas.',
    indications: 'Artritis reumatoide, osteoartritis, dolor muscular, dolor de cabeza, dolor menstrual.',
    contraindications: 'Evitar en caso de úlcera péptica activa, alergia a AINEs o en el tercer trimestre del embarazo.',
    dosage: 'Adultos: 1-2 tabletas cada 12 horas con alimentos. No exceder 1250mg al día.',
  },
  { 
    id: 13, 
    slug: 'loratadina-10mg',
    name: 'Loratadina 10mg',
    fullName: 'Loratadina 10mg (Caja x 10 tabletas)',
    code: '1002504SP',
    category: 'Medicinas',
    brand: 'Genérico',
    price: 3.20,
    oldPrice: 4.00,
    discount: 20,
    stock: 50,
    images: [
      'https://placehold.co/600x600/e3f2fd/1976d2?text=💊+Loratadina+10mg',
      'https://placehold.co/600x600/e3f2fd/1976d2?text=Caja+x+10',
      'https://placehold.co/600x600/e3f2fd/1976d2?text=Vista+Lateral',
    ],
    description: 'Antihistamínico de segunda generación para el alivio de síntomas alérgicos. No causa somnolencia.',
    indications: 'Rinitis alérgica, urticaria, picazón de piel, estornudos, lagrimeo por alergias.',
    contraindications: 'Hipersensibilidad a loratadina. Usar con precaución en insuficiencia hepática.',
    dosage: 'Adultos y niños mayores de 12 años: 1 tableta al día. Puede tomarse con o sin alimentos.',
  },
  { 
    id: 14, 
    slug: 'omeprazol-20mg',
    name: 'Omeprazol 20mg',
    fullName: 'Omeprazol 20mg (Caja x 14 cápsulas)',
    code: '1002505SP',
    category: 'Medicinas',
    brand: 'Genérico',
    price: 6.50,
    oldPrice: 8.00,
    discount: 19,
    stock: 40,
    images: [
      'https://placehold.co/600x600/e3f2fd/1976d2?text=💊+Omeprazol+20mg',
      'https://placehold.co/600x600/e3f2fd/1976d2?text=Caja+x+14',
      'https://placehold.co/600x600/e3f2fd/1976d2?text=Vista+Lateral',
    ],
    description: 'Inhibidor de la bomba de protones para el tratamiento de problemas de acidez estomacal y úlceras.',
    indications: 'Reflujo gastroesofágico, úlcera gástrica, úlcera duodenal, síndrome de Zollinger-Ellison.',
    contraindications: 'Hipersensibilidad al omeprazol. Usar con precaución en enfermedad hepática severa.',
    dosage: 'Adultos: 1 cápsula al día en ayunas, 30 minutos antes del desayuno. Tratamiento de 2-4 semanas.',
  },
  { 
    id: 15, 
    slug: 'losartan-50mg',
    name: 'Losartán 50mg',
    fullName: 'Losartán 50mg (Caja x 30 tabletas)',
    code: '1002506SP',
    category: 'Medicinas',
    brand: 'Genérico',
    price: 8.90,
    oldPrice: 11.00,
    discount: 19,
    stock: 35,
    images: [
      'https://placehold.co/600x600/e3f2fd/1976d2?text=💊+Losartán+50mg',
      'https://placehold.co/600x600/e3f2fd/1976d2?text=Caja+x+30',
      'https://placehold.co/600x600/e3f2fd/1976d2?text=Vista+Lateral',
    ],
    description: 'Antihipertensivo del grupo de antagonistas de receptores de angiotensina II para control de presión arterial.',
    indications: 'Hipertensión arterial, protección renal en diabéticos, insuficiencia cardíaca.',
    contraindications: 'Embarazo, hipersensibilidad al losartán, estenosis bilateral de arterias renales.',
    dosage: 'Adultos: 1 tableta al día. Puede aumentarse a 100mg según indicación médica.',
  },
  { 
    id: 16, 
    slug: 'metformina-850mg',
    name: 'Metformina 850mg',
    fullName: 'Metformina 850mg (Caja x 30 tabletas)',
    code: '1002507SP',
    category: 'Medicinas',
    brand: 'Genérico',
    price: 7.20,
    oldPrice: 9.00,
    discount: 20,
    stock: 28,
    images: [
      'https://placehold.co/600x600/e3f2fd/1976d2?text=💊+Metformina+850mg',
      'https://placehold.co/600x600/e3f2fd/1976d2?text=Caja+x+30',
      'https://placehold.co/600x600/e3f2fd/1976d2?text=Vista+Lateral',
    ],
    description: 'Antidiabético oral de primera línea para el tratamiento de diabetes mellitus tipo 2.',
    indications: 'Diabetes mellitus tipo 2, especialmente en pacientes con sobrepeso. Control de glucosa en sangre.',
    contraindications: 'Insuficiencia renal, insuficiencia hepática, alcoholismo, acidosis metabólica.',
    dosage: 'Adultos: Iniciar con 1 tableta al día con las comidas. Ajustar según respuesta.',
  },
  { 
    id: 17, 
    slug: 'diclofenaco-gel',
    name: 'Diclofenaco Gel',
    fullName: 'Diclofenaco Gel 1% (Tubo x 30g)',
    code: '1002502SP',
    category: 'Medicinas',
    brand: 'Genérico',
    price: 8.90,
    oldPrice: 11.00,
    discount: 19,
    stock: 22,
    images: [
      'https://placehold.co/600x600/e3f2fd/1976d2?text=💊+Diclofenaco+Gel',
      'https://placehold.co/600x600/e3f2fd/1976d2?text=Tubo+30g',
      'https://placehold.co/600x600/e3f2fd/1976d2?text=Vista+Lateral',
    ],
    description: 'Gel antiinflamatorio de uso tópico para aliviar dolor e inflamación localizada en músculos y articulaciones.',
    indications: 'Dolor muscular, esguinces, contusiones, tendinitis, artritis localizada, dolor post-traumático.',
    contraindications: 'No aplicar en heridas abiertas, piel irritada o con eczema. Evitar contacto con ojos.',
    dosage: 'Aplicar una capa fina 3-4 veces al día en la zona afectada. Masajear suavemente hasta absorción.',
  },

  // VITAMINAS
  { 
    id: 2, 
    slug: 'vitamina-c-1000mg',
    name: 'Vitamina C 1000mg',
    fullName: 'Vitamina C 1000mg (Frasco x 60 tabletas)',
    code: '1002508SP',
    category: 'Vitaminas',
    brand: 'Genérico',
    price: 15.00,
    oldPrice: 18.00,
    discount: 17,
    stock: 30,
    images: [
      'https://placehold.co/600x600/fff3e0/f57c00?text=🍊+Vitamina+C',
      'https://placehold.co/600x600/fff3e0/f57c00?text=Frasco+x+60',
      'https://placehold.co/600x600/fff3e0/f57c00?text=Vista+Lateral',
    ],
    description: 'Suplemento de vitamina C de alta potencia para reforzar el sistema inmunológico y propiedades antioxidantes.',
    indications: 'Prevención de resfriados, refuerzo del sistema inmune, antioxidante, mejora absorción de hierro.',
    contraindications: 'Hipersensibilidad a vitamina C. Usar con precaución en personas con cálculos renales.',
    dosage: 'Adultos: 1 tableta al día con las comidas. No exceder la dosis recomendada.',
  },
  { 
    id: 18, 
    slug: 'complejo-b',
    name: 'Complejo B',
    fullName: 'Complejo B (Frasco x 100 tabletas)',
    code: '1002509SP',
    category: 'Vitaminas',
    brand: 'Genérico',
    price: 12.50,
    oldPrice: 15.00,
    discount: 17,
    stock: 18,
    images: [
      'https://placehold.co/600x600/fff3e0/f57c00?text=💊+Complejo+B',
      'https://placehold.co/600x600/fff3e0/f57c00?text=Frasco+x+100',
      'https://placehold.co/600x600/fff3e0/f57c00?text=Vista+Lateral',
    ],
    description: 'Suplemento vitamínico con todas las vitaminas del complejo B para energía y función neurológica.',
    indications: 'Fatiga, estrés, mejora del metabolismo energético, salud del sistema nervioso.',
    contraindications: 'Hipersensibilidad a componentes del complejo B.',
    dosage: 'Adultos: 1 tableta al día con el desayuno.',
  },
  { 
    id: 19, 
    slug: 'omega-3',
    name: 'Omega 3',
    fullName: 'Omega 3 1000mg (Frasco x 60 cápsulas)',
    code: '1002510SP',
    category: 'Vitaminas',
    brand: 'Genérico',
    price: 22.00,
    oldPrice: 26.00,
    discount: 15,
    stock: 40,
    images: [
      'https://placehold.co/600x600/fff3e0/f57c00?text=🐟+Omega+3',
      'https://placehold.co/600x600/fff3e0/f57c00?text=Frasco+x+60',
      'https://placehold.co/600x600/fff3e0/f57c00?text=Vista+Lateral',
    ],
    description: 'Ácidos grasos esenciales EPA y DHA para salud cardiovascular, cerebral y articular.',
    indications: 'Salud cardiovascular, reducción de triglicéridos, salud cerebral, antiinflamatorio.',
    contraindications: 'Alergia al pescado. Usar con precaución si toma anticoagulantes.',
    dosage: 'Adultos: 1-2 cápsulas al día con las comidas.',
  },

  // BEBÉS
  { 
    id: 6, 
    slug: 'panales-etapa-3',
    name: 'Pañales Etapa 3',
    fullName: 'Pañales Etapa 3 (Paquete x 34 unidades)',
    code: '1002511SP',
    category: 'Bebés',
    brand: 'Huggies',
    price: 18.50,
    oldPrice: 22.00,
    discount: 16,
    stock: 50,
    images: [
      'https://placehold.co/600x600/fce4ec/c2185b?text=🍼+Pañales+E3',
      'https://placehold.co/600x600/fce4ec/c2185b?text=Paquete+x+34',
      'https://placehold.co/600x600/fce4ec/c2185b?text=Vista+Lateral',
    ],
    description: 'Pañales desechables con tecnología de absorción rápida y protección contra fugas para bebés de 6-10 kg.',
    indications: 'Para bebés que pesan entre 6 y 10 kg. Absorción superior por hasta 12 horas.',
    contraindications: 'Cambiar el pañal frecuentemente para evitar irritación de piel.',
    dosage: 'Usar según necesidad. Cambiar cada 3-4 horas o cuando esté mojado.',
  },
  { 
    id: 9, 
    slug: 'leche-nutribaby',
    name: 'Leche NutriBaby Premium 3',
    fullName: 'Leche NutriBaby Premium 3 (Lata x 900g)',
    code: '1002512SP',
    category: 'Bebés',
    brand: 'NutriBaby',
    price: 25.60,
    oldPrice: 32.00,
    discount: 20,
    stock: 12,
    images: [
      'https://placehold.co/600x600/fce4ec/c2185b?text=🍼+NutriBaby',
      'https://placehold.co/600x600/fce4ec/c2185b?text=Lata+900g',
      'https://placehold.co/600x600/fce4ec/c2185b?text=Vista+Lateral',
    ],
    description: 'Fórmula infantil de continuación fortificada con DHA, ARA y prebióticos para el desarrollo cerebral.',
    indications: 'Para bebés de 12 meses en adelante. Complemento de alimentación balanceada.',
    contraindications: 'No usar en caso de alergia a proteínas de leche de vaca.',
    dosage: 'Según indicación del pediatra. Preparar siguiendo instrucciones del empaque.',
  },
  { 
    id: 10, 
    slug: 'toallitas-humedas',
    name: 'Toallitas Húmedas',
    fullName: 'Toallitas Húmedas Bebé (Paquete x 80 unidades)',
    code: '1002513SP',
    category: 'Bebés',
    brand: 'Babysec',
    price: 7.50,
    oldPrice: 9.00,
    discount: 17,
    stock: 40,
    images: [
      'https://placehold.co/600x600/fce4ec/c2185b?text=🧻+Toallitas',
      'https://placehold.co/600x600/fce4ec/c2185b?text=Paquete+x+80',
      'https://placehold.co/600x600/fce4ec/c2185b?text=Vista+Lateral',
    ],
    description: 'Toallitas húmedas hipoalergénicas para la limpieza delicada de la piel del bebé.',
    indications: 'Limpieza de piel sensible del bebé. Con extractos naturales y sin alcohol.',
    contraindications: 'Evitar contacto con ojos. Suspender uso si hay irritación.',
    dosage: 'Usar según necesidad para limpieza del bebé.',
  },

  // CUIDADO PERSONAL
  { 
    id: 3, 
    slug: 'shampoo-anticaspa',
    name: 'Shampoo Anticaspa Pro-V',
    fullName: 'Shampoo Anticaspa Pro-V (Frasco x 400ml)',
    code: '1002514SP',
    category: 'Cuidado Personal',
    brand: 'Pantene',
    price: 8.75,
    oldPrice: 10.50,
    discount: 17,
    stock: 20,
    images: [
      'https://placehold.co/400x400/f3e5f5/7b1fa2?text=🧴+Shampoo',
      'https://placehold.co/400x400/f3e5f5/7b1fa2?text=Frasco+400ml',
      'https://placehold.co/400x400/f3e5f5/7b1fa2?text=Vista+Lateral',
    ],
    description: 'Shampoo especializado para eliminar la caspa y mantener el cuero cabelludo saludable.',
    indications: 'Caspa, picazón del cuero cabelludo, descamación. Uso diario.',
    contraindications: 'Evitar contacto con ojos. Suspender si hay irritación.',
    dosage: 'Aplicar sobre cabello mojado, masajear y enjuagar. Repetir si es necesario.',
  },
  { 
    id: 5, 
    slug: 'protector-solar-spf50',
    name: 'Protector Solar SPF 50',
    fullName: 'Protector Solar SPF 50 (Frasco x 120ml)',
    code: '1002515SP',
    category: 'Cuidado Personal',
    brand: 'Neutrogena',
    price: 22.00,
    oldPrice: 28.00,
    discount: 21,
    stock: 15,
    images: [
      'https://placehold.co/400x400/f3e5f5/7b1fa2?text=☀️+Protector',
      'https://placehold.co/400x400/f3e5f5/7b1fa2?text=Frasco+120ml',
      'https://placehold.co/400x400/f3e5f5/7b1fa2?text=Vista+Lateral',
    ],
    description: 'Protector solar de amplio espectro UVA/UVB resistente al agua para protección máxima.',
    indications: 'Protección solar diaria. Prevención de quemaduras y envejecimiento prematuro.',
    contraindications: 'Evitar contacto con ojos. Probar en área pequeña antes del uso.',
    dosage: 'Aplicar generosamente 15 minutos antes de exposición solar. Reaplicar cada 2 horas.',
  },
];

export default async function ProductPage({ 
  params 
}: { 
  params: Promise<{ slug: string }> 
}) {
  const resolvedParams = await params;
  const slug = resolvedParams.slug;

  // Buscar el producto
  const product = allProducts.find(p => p.slug === slug);

  if (!product) {
    return (
      <div className="container mx-auto px-4 py-16 text-center">
        <h1 className="text-3xl font-bold text-gray-800 mb-4">Producto no encontrado</h1>
        <p className="text-gray-600 mb-8">El producto que buscas no existe.</p>
      </div>
    );
  }

  // Productos relacionados
  const relatedProducts = allProducts
    .filter(p => p.category === product.category && p.id !== product.id)
    .slice(0, 4);

  return <ProductPageClient product={product} relatedProducts={relatedProducts} />;
}